### ISSUE TITLE
ImportError: No module named '__init__'

### ISSUE THREAD

**Issue by suhaib96** [ksharindam/quartz-browser#2]
ImportError while running on Ubuntu 16.10.

`Traceback (most recent call last):`
`  File "./run.py", line 2, in <module>`
`    from quartz_browser import main`
`  File "/home/suhaib/Desktop/quartz-browser-master/quartz_browser/main.py", line 4, in <module>`
`    from __init__ import __version__`
`ImportError: No module named '__init__'`

Python 2.7 and 3.6

**Comment by ksharindam** [comment]
Strange, i cant reproduce the issue in debian and raspbian.
Ok, i shall find out the problem, and will fix it soon.
